#!/bin/bash

baseurl="https://www.urbandictionary.com/define.php?term"
query="$(printf '%s' "$*")"
smul="$(tput smul)"
bold="$(tput bold)"
italic="$(tput sitm)"
normal="$(tput sgr 0)"

define=$(curl -s $baseurl=$query |
	grep -Eo "<div class=\"meaning mb-4\">.*" |
	sed "s/<div class=\"contributor.*//g;
	s/<a class[^>]*>/$smul/g;
	s/<\/a>/$normal/g;
	s/<\/div>/\n/g;
	s/&apos;/'/g;
	s/&quot;/\"/g;
	s/&amp;/\&/g;
	s/<div class=\"example[^>]*>/\n\n/g;
	s/<[^>]*>//g" |
	sed -e 's/\./\. /g; s/[ ][ ]*/ /g')

defineup=$(curl -s $baseurl=${query^} |
	grep -Eo "<div class=\"meaning mb-4\">.*" |
	sed "s/<div class=\"contributor.*//g;
	s/<a class[^>]*>/$smul/g; 
	s/<\/a>/$normal/g;
	s/<\/div>/\n/g;
	s/&apos;/'/g;
	s/&quot;/\"/g;
	s/&amp;/\&/g;
	s/<div class=\"example[^>]*>/\n\n/g;
	s/<[^>]*>//g" |
	sed -e 's/\./\. /g; s/[ ][ ]*/ /g')

if [ ! -z "$define" ]; then
	echo -e "\n$define\n"
fi

if [ ! -z "$defineup" ]; then
	echo -e "\n$defineup\n"
fi

if [ -z "$define" ] && [ -z "$defineup" ]; then
	echo -e "\nNot found. Try killing yourself\n"
fi
