#!/bin/bash

baseurl="https://www.urbandictionary.com/define.php?term"
query=$(printf '%s' "$*")
smul="$(tput smul)"
bold="$(tput bold)"
italic="$(tput sitm)"
normal="$(tput sgr 0)"

define=$(curl -s $baseurl=$query |
	grep -Po "<div class=\"meaning mb-4\">((.*?))<div class=\"contributor font-bold\">" |
	sed -r "s/<br\/>/\n/g;
	s/(<a class=\"autolink\" href=\"\/define\.php\?term\=[a-zA-Z0-9%-]+\">)/$smul/g;
	s/<\/a>/$normal/g;
	s/<div class=\"meaning mb-4\">/\n--------------------------------------------------------\n\n/g;
	s/&apos;/'/g;
	s/&quot;/\"/g;
	s/&amp;/\&/g;
	s/<div class=\"example italic mb-4\">/\n\n Example: /g;
	s/<[^>]*>//g")
#	s/\./\. /g; s/[ ][ ]*/ /g")

if [ ! -z "$define" ]; then
	echo -e "$define"
fi
